### ISSUE TITLE
Integration with ionic 3

### ISSUE THREAD

**Issue by bellalMohamed** [Instabug/instabug-cordova#48]
Is there any documentations for ionic 3 implementation

**Comment by ZiadAyman** [comment]
Hey @bellalMohamed 
Please accept our apologies on the late reply here. 

Ionic 3 implementation is basically the same as [Cordova's](https://docs.instabug.com/docs/cordova-overview) 
just instead of adding the plugin using `cordova plugin add instabug-cordova` add it using `ionic cordova plugin add instabug-cordova`.

And make sure that you have `declare let cordova: any;` declared in your app.component.ts file.

Please check it out and let me know if anything is not clear here!
